version: "3.8"

services:
  app:
    build:
      context: ./server
    container_name: fastify
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=postgresql://root:root@postgres:5432/root
    depends_on:
      postgres:
        condition: service_started
    working_dir: /usr/src/app
    networks:
      - app-network

  postgres:
    image: postgres:latest
    container_name: postgres-db
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: root
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  frontend:
    build:
      context: ./client2
    container_name: react-app
    ports:
      - "80:80"
    depends_on:
      - app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
    driver: local
