import type { Hairdresser } from "./hairdresser";

export const hairdressers: Hairdresser[] = [
  {
    id: 1,
    name: "Anna Kovács",
    specialty: "Hajvágás és Styling",
    rating: 4.8,
    hasAvailability: true,
    nextAvailable: "Ma, 14:00",
    appointments: ["09:00", "14:00", "16:00"],
  },
  {
    id: 2,
    name: "Péter Nagy",
    specialty: "Festés",
    rating: 4.6,
    hasAvailability: true,
    nextAvailable: "Ma, 16:00",
    appointments: ["10:00", "16:00"],
  },
  {
    id: 3,
    name: "Zsófia Tóth",
    specialty: "Hajhosszabbítás",
    rating: 4.9,
    hasAvailability: true,
    nextAvailable: "Holnap, 10:00",
    appointments: ["10:00", "11:30", "15:00"],
  },
  {
    id: 4,
    name: "István Szabó",
    specialty: "Férfi Hajvágás",
    rating: 4.7,
    hasAvailability: true,
    nextAvailable: "Ma, 18:00",
    appointments: ["12:00", "18:00"],
  },
  {
    id: 5,
    name: "Katalin Varga",
    specialty: "Esküvői Frizura",
    rating: 5.0,
    hasAvailability: true,
    nextAvailable: "Jövő Hét",
    appointments: ["10:30", "14:00"],
  },
  {
    id: 6,
    name: "Gábor Fekete",
    specialty: "Hajkezelés",
    rating: 4.5,
    hasAvailability: true,
    nextAvailable: "Holnap, 14:00",
    appointments: ["09:30", "14:00", "17:30"],
  },
  {
    id: 7,
    name: "Eszter Molnár",
    specialty: "Balayage",
    rating: 4.8,
    hasAvailability: true,
    nextAvailable: "Ma, 17:00",
    appointments: ["11:00", "17:00"],
  },
  {
    id: 8,
    name: "Tamás Balogh",
    specialty: "Szakállvágás",
    rating: 4.6,
    hasAvailability: true,
    nextAvailable: "Holnap, 11:00",
    appointments: ["11:00", "13:30", "16:00"],
  },
  {
    id: 9,
    name: "Viktória Kiss",
    specialty: "Melírozás",
    rating: 4.7,
    hasAvailability: true,
    nextAvailable: "Ma, 15:00",
    appointments: ["10:30", "15:00"],
  },
  {
    id: 10,
    name: "Dániel Horváth",
    specialty: "Fade Hajvágás",
    rating: 4.9,
    hasAvailability: true,
    nextAvailable: "Holnap, 09:00",
    appointments: ["09:00", "12:00", "15:30"],
  },
  {
    id: 11,
    name: "Júlia Németh",
    specialty: "Keratin Kezelés",
    rating: 4.8,
    hasAvailability: true,
    nextAvailable: "Ma, 13:00",
    appointments: ["13:00", "16:30"],
  },
  {
    id: 12,
    name: "Márton Farkas",
    specialty: "Hajformázás",
    rating: 4.5,
    hasAvailability: true,
    nextAvailable: "Holnap, 16:00",
    appointments: ["09:00", "13:00", "16:00"],
  },
  {
    id: 13,
    name: "Boglárka Papp",
    specialty: "Ombre",
    rating: 4.7,
    hasAvailability: true,
    nextAvailable: "Ma, 11:00",
    appointments: ["11:00", "15:30"],
  },
  {
    id: 14,
    name: "Zoltán Takács",
    specialty: "Férfi Szakáll",
    rating: 4.6,
    hasAvailability: true,
    nextAvailable: "Holnap, 13:00",
    appointments: ["13:00", "17:00"],
  },
  {
    id: 15,
    name: "Réka Simon",
    specialty: "Hajfestés",
    rating: 4.9,
    hasAvailability: true,
    nextAvailable: "Ma, 10:00",
    appointments: ["10:00", "14:30"],
  },
  {
    id: 16,
    name: "Attila Pintér",
    specialty: "Modern Vágás",
    rating: 4.7,
    hasAvailability: true,
    nextAvailable: "Holnap, 15:00",
    appointments: ["09:30", "15:00", "18:00"],
  },
  {
    id: 17,
    name: "Erika Szűcs",
    specialty: "Gyerek Hajvágás",
    rating: 4.8,
    hasAvailability: true,
    nextAvailable: "Ma, 12:00",
    appointments: ["12:00", "16:00"],
  },
  {
    id: 18,
    name: "Balázs Lakatos",
    specialty: "Klasszikus Vágás",
    rating: 4.5,
    hasAvailability: true,
    nextAvailable: "Holnap, 10:30",
    appointments: ["10:30", "14:00", "17:30"],
  },
  {
    id: 19,
    name: "Noémi Oláh",
    specialty: "Hajápolás",
    rating: 4.9,
    hasAvailability: true,
    nextAvailable: "Ma, 15:30",
    appointments: ["09:00", "15:30"],
  },
  {
    id: 20,
    name: "Krisztián Mészáros",
    specialty: "Férfi Trend",
    rating: 4.7,
    hasAvailability: true,
    nextAvailable: "Holnap, 12:30",
    appointments: ["12:30", "16:00"],
  },
  {
    id: 21,
    name: "Adrienn Szilágyi",
    specialty: "Alkalmi Frizura",
    rating: 4.8,
    hasAvailability: true,
    nextAvailable: "Ma, 13:30",
    appointments: ["13:30", "17:00"],
  },
  {
    id: 22,
    name: "Gergő Török",
    specialty: "Undercut",
    rating: 4.6,
    hasAvailability: true,
    nextAvailable: "Holnap, 09:30",
    appointments: ["09:30", "13:00", "16:30"],
  },
  {
    id: 23,
    name: "Fanni Boros",
    specialty: "Hajfonás",
    rating: 4.9,
    hasAvailability: true,
    nextAvailable: "Ma, 11:30",
    appointments: ["11:30", "15:00"],
  },
  {
    id: 24,
    name: "Levente Hegedűs",
    specialty: "Férfi Klasszikus",
    rating: 4.7,
    hasAvailability: true,
    nextAvailable: "Holnap, 14:30",
    appointments: ["10:00", "14:30", "17:00"],
  },
  {
    id: 25,
    name: "Dorina Deák",
    specialty: "Hajsimítás",
    rating: 4.8,
    hasAvailability: true,
    nextAvailable: "Ma, 16:30",
    appointments: ["12:00", "16:30"],
  },
  {
    id: 26,
    name: "Máté Halász",
    specialty: "Férfi Modern",
    rating: 4.6,
    hasAvailability: true,
    nextAvailable: "Holnap, 11:30",
    appointments: ["11:30", "15:00", "18:30"],
  },
  {
    id: 27,
    name: "Kinga Fodor",
    specialty: "Hajgöndörítés",
    rating: 4.9,
    hasAvailability: true,
    nextAvailable: "Ma, 10:30",
    appointments: ["10:30", "14:00"],
  },
  {
    id: 28,
    name: "Bence Orbán",
    specialty: "Férfi Divat",
    rating: 4.7,
    hasAvailability: true,
    nextAvailable: "Holnap, 13:30",
    appointments: ["09:00", "13:30", "17:00"],
  },
  {
    id: 29,
    name: "Lilla Bálint",
    specialty: "Hajdúsítás",
    rating: 4.8,
    hasAvailability: true,
    nextAvailable: "Ma, 12:30",
    appointments: ["12:30", "16:00"],
  },
  {
    id: 30,
    name: "Ádám Kelemen",
    specialty: "Férfi Elegáns",
    rating: 4.6,
    hasAvailability: true,
    nextAvailable: "Holnap, 10:00",
    appointments: ["10:00", "13:30", "17:30"],
  },
];
